#+TITLE: Wire Cell Exchange Data in ROOT format

This package provides data structures for exchanging data in ROOT format between Wire Cell and other systems.

This package is independent from Wire Cell Toolkit (and Prototype).

* Install

This package uses a custom [[https://waf.io/][waf]] command called =wcb=.  

#+BEGIN_SRC sh
  git clone https://github.com/WireCell/wire-cell-xdata-root.git
  # or git clone git@github.com:WireCell/wire-cell-xdata-root.git
  cd wire-cell-xdata-root/
  ./wcb --prefix=/path/to/install configure build install
#+END_SRC

** For Wire Cell Prototype

To build the [[https://github.com/BNLIF/wire-cell][Wire Cell prototype]] against this package choose =--prefix= to be the same as used to build that package and it will pick it up.

In the prototype, its use can be seen in the [[https://github.com/BNLIF/wire-cell-2dtoy/blob/master/apps/2dtoy-shower3d-xdata.cxx][2dtoy-shower3d-xdata]] app which can convert from an internal data format.

** For Wire Cell Toolkit

t.b.d.

* Overview of data

Top level object is =XdataFile= which helps maintain three main objects that map to =TTree= branches:

- =RunInfo= :: meta information about the DAQ or simulation "run"
- =Geom= :: static geometry information (wires)
- =Image= :: reconstructed image of one readout or "frame"

** Geom

The =Geom= data is (for now) simply a vector of Wire geometry information.  

** Image

The Image data is dynamic in the sense that it spans a "frame" of readout.  It makes reference to the static Geom information.

- =Deco= :: information about deconvoluted waveform information on a given wire in a time slice.

- =Cell= :: geometry information about a 2D cell and its relationships with wire geometry.  Note, this collection of cells is shared through the time slices of the frame but not between frames.  These cells do not contain any charge or other "dynamic" information.

- =Blob= :: an association between a collection of cells, a time slice and some numeric values (eg, charge)

- =Field= :: a collection of =FieldPoint= objects each of which associate a vector of numbers and a 3D point.  Fields have human readable names.
